djangoLoan/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import (
    CreateUserView, 
    RedirectDashboardView, 
    CustomLoginView, 
    FirstLoginView, 
    CustomLogoutView, 
    UserDashboardView,
    AdvisorDashboardView,
    UserListView,
    UserEditProfileView,
    UserView
    )

app_name = 'accounts' 

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('first_login/', FirstLoginView.as_view(), name='first_login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('dashboard/', RedirectDashboardView.as_view(), name='dashboard'),
    path('advisor/dashboard/', AdvisorDashboardView.as_view(), name='advisor_dashboard'),
    path('user/dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user/edit/<uuid:pk>/', UserEditProfileView.as_view(), name='user_edit'),
    path('user/<uuid:pk>/', UserView.as_view(), name='profil'),
    path('advisor/create_user/', CreateUserView.as_view(), name='create_user'),
    path('advisor/list_user/', UserListView.as_view(), name='list_users'),
]

#     path('dashboard/', views.dashboard_view, name='user_dashboard'),

djangoLoan/accounts/templates/accounts/advisor_dashboard.html
{% extends 'base.html' %}

{% block title %}Tableau de bord Conseiller{% endblock %}

{% block content %}
<div class="bg-white rounded-lg shadow p-6">
    <h2 class="text-2xl font-bold mb-6">Mon espace conseiller</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="border rounded p-4">
            <h3 class="text-lg font-semibold mb-4">Créer un nouveau client</h3>
            <form action="{% url 'accounts:create_user' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="nav-link">nouveau client</button>
            </form>
        </div>
        <div class="border rounded p-4">
            <h3 class="text-lg font-semibold mb-4">Vos clients</h3>
            <form action="{% url 'accounts:list_users' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="nav-link">voir vos clients</button>
            </form>
        </div>
    </div>
</div>
</div>

{% endblock %}

djangoLoan/accounts/templates/accounts/client_dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="bg-white rounded-lg shadow p-6">
    <h2 class="text-2xl font-bold mb-6">Mon espace client</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="border rounded p-4">
            <h3 class="text-lg font-semibold mb-4">Ma demandes de garantie de prêt</h3>
            {% if loan.status == "en attente" %}
                <span>
                    Votre demande est en cours de traitement
                    <form action="{% url 'loans:loan_update' pk=request.user.loan.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="nav-link">modifier ma demande</button>
                    </form>
                </span>
            {% elif loan.status == "refusé" %}
                <p>Votre demande a été refusé</p>
            {% elif loan.status == "accepté" %}
                <p>Votre demande a été accepté</p>
            {% else %}
                <span>
                    Vous n'avez pas encore fait de demande
                    <form action="{% url 'loans:loan_create' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="nav-link">faire une demande</button>
                    </form>
                </span>
            {% endif %}
        </div>
        <div class="border rounded p-4">
            <h3 class="text-lg font-semibold mb-4">Profil</h3>
            <a class="nav-link" href="{% url 'accounts:profil' pk=request.user.id %}">Voir mon profil</a>
            <a class="nav-link" href="{% url 'accounts:user_edit' pk=request.user.id %}">Modifier mon profil</a>
        </div>
    </div>
</div>
</div>

{% endblock %}

djangoLoan/accounts/templates/accounts/client_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="bg-white rounded-lg shadow p-6">
    <h2 class="text-2xl font-bold mb-6">Les clients</h2>

    <table class="w-full text-sm text-center rtl:text-right text-gray-500 dark:text-gray-400" border="1">
        <thead>
            <tr class="text-lg">
                <th>Nom de la compagnie</th>
                <th>Email</th>
                <th>Status de la demande</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    {% if user.loan %}
                    <td><p>status de la demande : {{ user.loan.status }}</p>
                    <form action="{% url 'loans:advisor_loan' pk=user.loan.id %}" method="get">
                        {% csrf_token %}
                        <button type="submit" class="nav-link">Détail</button>
                    </form></td>
                    {% else  %}
                    <td><p>Cette entreprise n'a pas encore fait de demande</p></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

djangoLoan/accounts/templates/accounts/create_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post">
    <div class="mb-3">
        <h1>Créer un compte client</h1>
    </div>

    {% csrf_token %}

    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
        {{ form.email }}
      <div id="email" class="form-text">Saisissez une adresse mail valide</div>
    </div>

    <div class="mb-3">
        <label for="username" class="form-label">Nom de l'entreprise</label>
        {{ form.username }}
        <div id="username" class="form-text">Saisissez le nom de l'entreprise</div>
    </div>

    <div class="mb-3">
        <label for="last_name" class="form-label">Nom</label>
        {{ form.last_name }}
        <div id="last_name" class="form-text">Saisissez un nom</div>
    </div>

    <div class="mb-3">
        <label for="first_name" class="form-label">Prénom</label>
        {{ form.first_name }}
        <div id="first_name" class="form-text">Saisissez un prénom</div>
    </div>

    <div class="mb-3">
        <label for="phone_number" class="form-label">Numéro de téléphone</label>
        {{ form.phone_number }}
        <div id="phone_number" class="form-text">Saisissez un numéro de téléphone</div>
    </div>

    <button type="submit" class="btn btn-dark"><b>Créer le compte</b></button>
</form>
</div>

{% endblock %}

djangoLoan/accounts/templates/accounts/first_login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Première connexion</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-4">
            <label for="new_password">Nouveau mot de passe</label>
            {{ form.new_password }}
        </div>
        <div class="form-group">
            <label for="confirm_new_password">Confirmer le mot de passe</label>
            {{ form.confirm_new_password }}
        </div>
        <button type="submit" class="btn btn-primary">Changer son mot de passe</button>
    </form>
    
</div>
{% endblock %}

djangoLoan/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Connexion</h2>
    <form method="post">
        {% csrf_token %}
{% comment "" %}
        <div class="form-group">
            <label for="username">Email</label>
            {{ form.username }}
            {% endcomment %}
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Email</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="password">Mot de passe</label>
            {{ form.password }}
        </div>
        <button type="submit" class="btn btn-primary">Se connecter</button>
    </form>
    
</div>
{% endblock %}

djangoLoan/accounts/templates/accounts/profil.html
{% extends 'base.html' %}

{% block content %}
  <div class="profile-container">
    <h1>Profil de {{ user.username }}</h1>

    <div class="profile-details">
      <div class="profile-picture">
        {% if user.profile_picture %}
          <img src="{{ user.profile_picture.url }}" alt="Photo de profil" class="profile-img">
        {% endif %}
      </div>

      <div class="profile-info">
        <p><strong>Nom de l'entreprise :</strong> {{ user.username }}</p>
        <p><strong>Prénom :</strong> {{ user.first_name }}</p>
        <p><strong>Nom :</strong> {{ user.last_name }}</p>
        <p><strong>Email :</strong> {{ user.email }}</p>
        <p><strong>Numéro de téléphone :</strong> {{ user.phone_number }}</p>
      </div>
    </div>
    <div class="profile-actions">
      <a href="{% url 'accounts:user_edit' pk=request.user.id %}" class="btn btn-primary">Modifier le profil</a>
    </div>
  </div>
{% endblock %}

djangoLoan/accounts/templates/accounts/profil_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post" class="bg-white p-6 rounded-lg shadow-md" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        {{form.as_p}}
    </div>
    <br></br>
    <button type="submit" class="btn text-lg">Envoyer</button>
</form>
</div>

{% endblock %}