djangoLoan/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import (
    CreateUserView, 
    RedirectDashboardView, 
    CustomLoginView, 
    FirstLoginView, 
    CustomLogoutView, 
    UserDashboardView,
    AdvisorDashboardView,
    UserListView,
    UserEditProfileView,
    UserView
    )

app_name = 'accounts' 

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('first_login/', FirstLoginView.as_view(), name='first_login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('dashboard/', RedirectDashboardView.as_view(), name='dashboard'),
    path('advisor/dashboard/', AdvisorDashboardView.as_view(), name='advisor_dashboard'),
    path('user/dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user/edit/<uuid:pk>/', UserEditProfileView.as_view(), name='user_edit'),
    path('user/<uuid:pk>/', UserView.as_view(), name='profil'),
    path('advisor/create_user/', CreateUserView.as_view(), name='create_user'),
    path('advisor/list_user/', UserListView.as_view(), name='list_users'),
]

#     path('dashboard/', views.dashboard_view, name='user_dashboard'),

djangoLoan/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_room, name='chat_room'),
    path('api/messages/', views.message_list, name='message_list'),
    path('api/send/', views.send_message, name='send_message'),
    path('send/', views.send_message, name='send_message'),
    path('messages/', views.message_list, name='message_list'),
    path('api/private/messages/', views.private_message_list, name='api_private_message_list'),
    path('api/private/send/', views.send_private_message, name='send_private_message'),
]

djangoLoan/djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf import settings
from djangoApp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('loans/', include('loans.urls')),
    path('news/', include('news.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoLoan/news/urls.py
from django.urls import path
from news.views import get_all_news, news_detail, create_news, update_news, news_by_user, delete_news

app_name = 'news'

urlpatterns = [
    path("", get_all_news, name="all_news"),
    path("me/", news_by_user, name="my_news"),
    path("add/", create_news, name="create_news"),
    path("<int:id>/", news_detail, name="news_detail"),
    path("edit/<int:id>/", update_news, name="updated_news"),
    path("delete/<int:id>/", delete_news, name="delete_news")
]

djangoLoan/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{% static 'images/logo.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">  <b>A loan in the dark</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% comment %} <img src="{{ request.user.profile_picture.url }}" alt="Profile Picture" class="rounded-circle" width="40" height="40"> {% endcomment %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:all_news' %}">Actualités</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'chat:chat_room' %}">Chat</a> 
                </li>
                <li class="nav-item">
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link">Logout</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <form action="{% url 'accounts:login' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link">Login</button>
                    </form>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</nav>