djangoLoan/loans/urls.py
from django.urls import path
from loans.views import LoanCreateView, LoanUserView, AdvisorLoanDetailView, UpdateStatusLoanView,LoanUpdateView

app_name = 'loans' 

urlpatterns = [
    path('create/', LoanCreateView.as_view(), name='loan_create'),
    path('update/<uuid:pk>/', LoanUpdateView.as_view(), name='loan_update'),
    path('user_loan/', LoanUserView.as_view(), name='user_loan'),
    path('advisor/loan/<uuid:pk>/', AdvisorLoanDetailView.as_view(), name='advisor_loan'),
    path('advisor/loan/<uuid:pk>/update/', UpdateStatusLoanView.as_view(), name='update'),
]

djangoLoan/loans/templates/loans/advisor_loan.html
{% extends 'base.html' %}

{% block content %}
<script src="https://cdn.plot.ly/plotly-2.30.0.min.js"></script>
<div class="container">
    <h2 class="text-center">Résultats de la prediction :</h2>
    
    <table class="table table-striped">
        <tr>
            <th>prédiction</th>
            <td>{% if loan.prediction == 1 %}
                L'utilisateur va rembourser
            {% else %}
                L'utilisateur va être en défaut de paiement
            {% endif %}</td>
        </tr>
        <tr>
            <th>probabilité qu'il rembourse :</th>
            <td>{{ loan.proba_yes }}</td>
        </tr>
        <tr>
            <th>probabilité qu'il soit en défaut de paiement :</th>
            <td>{{ loan.proba_no }}</td>
        </tr>
    </table>

    <div class="container">
        <h2>Graphique des SHAP Values</h2>
        <div id="shap-plot"></div>
    </div>

    <div class="container text-center mb-5">
        {% if  loan.status == "accepté" %}
        <p>Vous avez validé cette garantie</p>
        <a href="{% url 'loans:update' pk=loan.id %}?action=reject" class="btn btn-primary">
            Refuser la garantie
        </a>
        {% elif loan.status == "refusé" %}
        <p>Vous avez refusé cette garantie</p>
        <a href="{% url 'loans:update' pk=loan.id %}?action=validate" class="btn btn-primary">
            Valider la garantie
        </a>
        {% else %}
        <a href="{% url 'loans:update' pk=loan.id %}?action=validate" class="btn btn-primary">
            Valider la garantie
        </a>
        <a href="{% url 'loans:update' pk=loan.id %}?action=reject" class="btn btn-primary">
            Refuser la garantie
        </a>
        {% endif %}
    </div>

    <h2 class="text-center">Détails du Prêt</h2>
    
    <table class="table table-striped">
        <tr>
            <th>ID du prêt</th>
            <td>{{ loan.id }}</td>
        </tr>
        <tr>
            <th>État</th>
            <td>{{ loan.state }}</td>
        </tr>
        <tr>
            <th>Banque</th>
            <td>{{ loan.bank }}</td>
        </tr>
        <tr>
            <th>NAICS</th>
            <td>{{ loan.naics }}</td>
        </tr>
        <tr>
            <th>Ligne de crédit</th>
            <td>{% if loan.rev_line_cr == 1 %} Oui {% else %} Non {% endif %}</td>
        </tr>
        <tr>
            <th>Low Doc</th>
            <td>{% if loan.low_doc == 1 %} Oui {% else %} Non {% endif %}</td>
        </tr>
        <tr>
            <th>Nouvelle entreprise</th>
            <td>{% if loan.new_exist == 1 %} Oui {% else %} Non {% endif %}</td>
        </tr>
        <tr>
            <th>A une franchise</th>
            <td>{% if loan.has_franchise == 1 %} Oui {% else %} Non {% endif %}</td>
        </tr>
        <tr>
            <th>Récession</th>
            <td>{% if loan.recession == 1 %} Oui {% else %} Non {% endif %}</td>
        </tr>
        <tr>
            <th>Zone Urbaine/Rurale</th>
            <td>{% if loan.urban_rural == 1 %} Urbaine {% else %} Rurale {% endif %}</td>
        </tr>
        <tr>
            <th>Emplois créés</th>
            <td>{{ loan.create_job }}</td>
        </tr>
        <tr>
            <th>Emplois maintenus</th>
            <td>{{ loan.retained_job }}</td>
        </tr>
        <tr>
            <th>Nombre d'employés</th>
            <td>{{ loan.no_emp }}</td>
        </tr>
        <tr>
            <th>Durée du prêt (mois)</th>
            <td>{{ loan.term }}</td>
        </tr>
        <tr>
            <th>Montant approuvé</th>
            <td>{{ loan.gr_appv }} €</td>
        </tr>
    </table>

</div>


<script>
    var graph = {{ graph_json|safe }};
    console.log(graph);
    Plotly.newPlot("shap-plot", graph);
</script>
{% endblock %}

djangoLoan/loans/templates/loans/loan_update.html
{% extends 'base.html' %}

{% block content %}
<div class="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md">
    <h2 class="text-2xl font-bold mb-6">Modifier la demande de garantie de pret</h2>
    <form method="post" class="bg-white p-6 rounded-lg shadow-md" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            {{form.as_p}}
        </div>
        <br></br>
        <button type="submit" class="btn text-lg">Envoyer</button>
    </form>
</div>
{% endblock %}

djangoLoan/loans/templates/loans/user_loan.html
{% extends 'base.html' %}

{% block content %}
<div class="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md">
    <p>Votre demande est en cours de traitement</p>
</div>
{% endblock %}