djangoLoan/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import (
    CreateUserView, 
    RedirectDashboardView, 
    CustomLoginView, 
    FirstLoginView, 
    CustomLogoutView, 
    UserDashboardView,
    AdvisorDashboardView,
    UserListView,
    UserEditProfileView,
    UserView
    )

app_name = 'accounts' 

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('first_login/', FirstLoginView.as_view(), name='first_login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('dashboard/', RedirectDashboardView.as_view(), name='dashboard'),
    path('advisor/dashboard/', AdvisorDashboardView.as_view(), name='advisor_dashboard'),
    path('user/dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user/edit/<uuid:pk>/', UserEditProfileView.as_view(), name='user_edit'),
    path('user/<uuid:pk>/', UserView.as_view(), name='profil'),
    path('advisor/create_user/', CreateUserView.as_view(), name='create_user'),
    path('advisor/list_user/', UserListView.as_view(), name='list_users'),
]

#     path('dashboard/', views.dashboard_view, name='user_dashboard'),

djangoLoan/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_room, name='chat_room'),
    path('api/messages/', views.message_list, name='message_list'),
    path('api/send/', views.send_message, name='send_message'),
    path('send/', views.send_message, name='send_message'),
    path('messages/', views.message_list, name='message_list'),
    path('api/private/messages/', views.private_message_list, name='api_private_message_list'),
    path('api/private/send/', views.send_private_message, name='send_private_message'),
]

djangoLoan/djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf import settings
from djangoApp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('loans/', include('loans.urls')),
    path('news/', include('news.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoLoan/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!--navbar-->
    <header>
        {% include 'includes/header.html' %}
    </header>
    {% comment %} <title>{% block title %}Bank App{% endblock %}</title>
    <style>
        /* Vos styles CSS ici */
    </style>
</head>
<body>
    <nav>
        <div class="nav-container">
            <a href="{% url 'accounts:dashboard' %}" class="nav-brand">BankApp</a>
            {% if request.session.token %}
                <div class="nav-links">
                    <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
                    {% if request.session.user_is_staff %}
                        <a href="#">Demandes</a>  <!-- Lien temporaire -->
                    {% else %}
                        <a href="#">Mon Compte</a>  <!-- Lien temporaire -->
                    {% endif %}
                    <a href="{% url 'chat:chat_room' %}">Chat</a>  <!-- Nouveau lien vers le chat -->
                    <a href="{% url 'accounts:logout' %}">Déconnexion</a>
                </div>
            {% endif %}
        </div>
    </nav> {% endcomment %}

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <main class="container">
        {% block content %}
        {% endblock %}
        {% if messages %}
    <div class="alert alert-danger mt-3">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %} 
    </main>

    {% block javascript %}{% endblock %}
</body>
</html>

djangoLoan/templates/home.html
{% block title %}Home page{% endblock %}

{% block content %}

{% endblock %}